spring.application.name=gym-track

spring.datasource.url=jdbc:postgresql://db:5432/gymtrack-db
spring.datasource.username=postgres
spring.datasource.password=1211
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never

spring.jpa.show-sql=true
spring.jpa.format-sql=true
